# Generated by Django 5.1.4 on 2024-12-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(blank=True, choices=[('Moroccan', 'Moroccan'), ('Italien', 'Italien'), ('Japanese', 'Japanes'), ('USA', 'USA')], max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cuisine'),
        ),
    ]
