# Generated by Django 5.1.2 on 2024-12-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cuisine_food_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='cuisine',
            new_name='name',
        ),
    ]
